In [ ]:
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from xgboost import XGBRegressor

In [ ]:
df = pd.read_excel('df.xlsx')
df

,Reference,DOI,Alginate (%w/v),PVA-HA (%w/v),CaSO4 (%w/v),Na2HPO4 (%w/v),Gelatin (%w/v),GelMA (%w/v),laponite (%w/v),graphene oxide (%w/v),...,Extrusion_Rate_Lengthwise_(mm/s),Extrusion_Rate_Volume-wise_(mL/s),Nozzle_Movement_Speed_(mm/s),Nozzle_Diameter_(µm),chamber Temperature (°C),Syringe_Temperature_(°C),Substrate_Temperature_(°C),Printability,Cell Response,Scaffold Quality (P*C)
0,Fedorovich et. al. 2008,10.1089/ten.a.2007.0158,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.67,NaN,15.0,210.0,NaN,22.0,22.0,3,3,9
1,Fedorovich et. al. 2008,10.1089/ten.a.2007.0158,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.67,NaN,15.0,210.0,NaN,22.0,22.0,3,5,15
2,Fedorovich et. al. 2008,10.1089/ten.a.2007.0158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.67,NaN,15.0,210.0,NaN,4.0,22.0,3,3,9
3,Fedorovich et. al. 2008,10.1089/ten.a.2007.0158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.67,NaN,15.0,210.0,NaN,4.0,22.0,3,4,12
4,Fedorovich et. al. 2008,10.1089/ten.a.2007.0158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.67,NaN,15.0,610.0,NaN,4.0,22.0,3,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,Lee et al. 2022,10.1016/j.ceramint.2021.12.227,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.5,...,10.00,NaN,NaN,510.0,NaN,45.0,NaN,2,1,2
1167,Lee et al. 2022,10.1016/j.ceramint.2021.12.227,0.0,0.0,0.0,0.0,20.0,0.0,0.0,1.0,...,1.00,NaN,NaN,510.0,NaN,47.5,NaN,1,1,1
1168,Lee et al. 2022,10.1016/j.ceramint.2021.12.227,0.0,0.0,0.0,0.0,20.0,0.0,0.0,1.0,...,2.00,NaN,NaN,510.0,NaN,47.5,NaN,2,1,2
1169,Lee et al. 2022,10.1016/j.ceramint.2021.12.227,0.0,0.0,0.0,0.0,20.0,0.0,0.0,1.0,...,3.00,NaN,NaN,510.0,NaN,47.5,NaN,3,1,3
1170,Lee et al. 2022,10.1016/j.ceramint.2021.12.227,0.0,0.0,0.0,0.0,20.0,0.0,0.0,1.0,...,4.00,NaN,NaN,510.0,NaN,47.5,NaN,2,1,2

In [ ]:
unique_values = df['Cell Type'].unique()
print(unique_values)

['bMSCs' 'NoCellCultured' 'RSC96/HUVECs' 'hASCs' 'RAMECs' 'L929' 'U87-MG'
 'chondrocyteyte' 'Schwann cells' 'hNCs' 'MG-63' 'MC3T3-E1' 'HNDF'
 '10T1/2' 'SMCs' 'VICs' 'HepG2' 'NIH3T3' 'hTMSCs' 'Myoblast cells'
 'HUVECs' 'ACPCs' 'HACs' 'hUVECs/NIH3T3' 'ESCs' 'HEPG2/ECs' 'EPCs' 'CPCs'
 'HUVSMCs' 'HUVECs/MSCs' 'bMSCs/hACs' 'MC3T3' 'SU3' 'U87'
 'pancreatic islets cells' 'hTERT-MSC' 'basil plant cell' 'hESCs' 'hiPSCs'
 'hESC-derived HLCs' 'hiPSCs-derived HLCs' 'ATDC5' 'RHECs' 'HeLa' 'MESCs'
 'dermal fibroblasts' 'Endothelial cells' 'Saos-2 ' 'NSCLC PDX'
 'NSCLC PDX/CAFs']

In [ ]:
category_mapping = dict(enumerate(df['Cell Type'].astype('category').cat.categories))
pd.DataFrame({
    'Cell Type':category_mapping.values(),
    'label':category_mapping.keys()}).to_excel('Cell_labels.xlsx', index=False)

In [ ]:
df['Cell Type'] = df['Cell Type'].astype('category').cat.codes

In [ ]:
df = df.drop(columns=['Reference', 'DOI'])

<h3>Applying Iterative Imputer with XGboost regression</h3>

In [ ]:
imputer = IterativeImputer(estimator=XGBRegressor(), max_iter=1000, random_state=0)
imputer.fit(df)
imputed_data_xgb = imputer.transform(df)
imputed_df_xgb = pd.DataFrame(imputed_data_xgb, columns=df.columns)

In [ ]:
imputed_df_xgb.to_excel('imputed_df_xgb_1000iteration.xlsx', index=False)

In [ ]:
data =pd.read_excel('imputed_df_xgb_1000iteration.xlsx')

In [ ]:
data

,Alginate (%w/v),PVA-HA (%w/v),CaSO4 (%w/v),Na2HPO4 (%w/v),Gelatin (%w/v),GelMA (%w/v),laponite (%w/v),graphene oxide (%w/v),hydroxyapatite (%w/v),Hyaluronic_Acid (%w/v),...,Extrusion_Rate_Lengthwise_(mm/s),Extrusion_Rate_Volume-wise_(mL/s),Nozzle_Movement_Speed_(mm/s),Nozzle_Diameter_(µm),chamber Temperature (°C),Syringe_Temperature_(°C),Substrate_Temperature_(°C),Printability,Cell Response,Scaffold Quality (P*C)
0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,16.67,0.034630,15.000000,210.0,4.000123,22.0,22.000000,3,3,9
1,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,16.67,0.034630,15.000000,210.0,4.000123,22.0,22.000000,3,5,15
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,16.67,0.036443,15.000000,210.0,4.000123,4.0,22.000000,3,3,9
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,16.67,0.036443,15.000000,210.0,4.000123,4.0,22.000000,3,4,12
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,16.67,0.065115,15.000000,610.0,22.499779,4.0,22.000000,3,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.5,70,0.0,...,10.00,0.146436,8.521680,510.0,7.000030,45.0,14.612704,2,1,2
1167,0.0,0.0,0.0,0.0,20.0,0.0,0.0,1.0,70,0.0,...,1.00,0.143146,1.785969,510.0,7.000030,47.5,20.812840,1,1,1
1168,0.0,0.0,0.0,0.0,20.0,0.0,0.0,1.0,70,0.0,...,2.00,0.143146,1.902900,510.0,7.000030,47.5,20.178131,2,1,2
1169,0.0,0.0,0.0,0.0,20.0,0.0,0.0,1.0,70,0.0,...,3.00,0.143146,1.380094,510.0,7.000030,47.5,20.047428,3,1,3
1170,0.0,0.0,0.0,0.0,20.0,0.0,0.0,1.0,70,0.0,...,4.00,0.143146,2.192616,510.0,7.000030,47.5,18.605902,2,1,2

<h3>Before applying IterativeImputer</h3>

In [ ]:
null_columns = df.columns[df.isnull().any()].tolist()
print("Columns with null values:", null_columns)

Columns with null values: ['Cell_Density_(cells/mL)', 'Extrusion_Pressure (kPa)', 'Extrusion_Rate_Lengthwise_(mm/s)', 'Extrusion_Rate_Volume-wise_(mL/s)', 'Nozzle_Movement_Speed_(mm/s)', 'Nozzle_Diameter_(µm)', 'chamber Temperature  (°C)', 'Syringe_Temperature_(°C)', 'Substrate_Temperature_(°C)']

<h3>After applying IterativeImputer</h3>

In [ ]:
null_columns = data.columns[data.isnull().any()].tolist()
print("Columns with null values:", null_columns)

Columns with null values: []